# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.6

    - name: Build
      run: |
        sudo apt-get -yqq install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Bundler Audit Action
      uses: andrewmcodes/bundler-audit-action@v0.0.1

    - name: Rubocop
      run: |
        bundle exec rubocop
