# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup ruby
      uses: actions/setup-ruby@v1.0.0
      with:
        version: 2.6

    - name: build
      run: |
        sudo apt-get update
        sudo apt-get -yqq install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: audit
      uses: andrewmcodes/bundler-audit-action@v0.0.1

    - name: rubocop
      run: |
        bundle exec rubocop

    - name: rspec:all
      run: |
        bundle exec rspec
